//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccessLayer.DataEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountDetail()
        {
            this.ProjectDetails = new HashSet<ProjectDetail>();
        }
    
        public int AccountDetailId { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> VerticalId { get; set; }
        public Nullable<int> Director { get; set; }
        public Nullable<int> SDM { get; set; }
        public Nullable<int> PM { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Vertical Vertical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectDetail> ProjectDetails { get; set; }
    }
}
