//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccessLayer.DataEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResourceDetail()
        {
            this.ResourceAllocations = new HashSet<ResourceAllocation>();
            this.VacationDetails = new HashSet<VacationDetail>();
        }
    
        public int ResourceDetailId { get; set; }
        public Nullable<int> PSAId { get; set; }
        public string ResourceName { get; set; }
        public Nullable<System.DateTime> CGIDateOfJoin { get; set; }
        public Nullable<System.DateTime> CareerStartDate { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> SkillFamilyId { get; set; }
        public Nullable<int> CompentencyId { get; set; }
        public Nullable<int> SubcompetencyId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ExtNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> DesignationId { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceAllocation> ResourceAllocations { get; set; }
        public virtual Status Status { get; set; }
        public virtual Subcompetency Subcompetency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacationDetail> VacationDetails { get; set; }
    }
}
