//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccessLayer.DataEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceAllocation
    {
        public int ResourceAllocationId { get; set; }
        public Nullable<int> ResourceDetailId { get; set; }
        public Nullable<int> ProjectDetailId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> ProjectRoleId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> HourPerDay { get; set; }
        public Nullable<bool> IsInShift { get; set; }
        public Nullable<int> ShiftDetailId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ProjectDetail ProjectDetail { get; set; }
        public virtual ProjectRole ProjectRole { get; set; }
        public virtual ResourceDetail ResourceDetail { get; set; }
        public virtual ShiftDetail ShiftDetail { get; set; }
        public virtual Status Status { get; set; }
    }
}
