//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccessLayer.DataEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class stg_ResourceDetail
    {
        public int Id { get; set; }
        public string ResourceID { get; set; }
        public string ResourceName { get; set; }
        public string DOJ { get; set; }
        public string Designation { get; set; }
        public string ShortDesignation { get; set; }
        public string TGGroup { get; set; }
        public string CGIExp { get; set; }
        public string PrevExp { get; set; }
        public string TotalExp { get; set; }
        public string MemberType { get; set; }
        public string Location { get; set; }
        public string Skillsfamily { get; set; }
        public string Competency { get; set; }
        public string Subcompetency { get; set; }
        public string SkillCategory { get; set; }
        public string HRBU { get; set; }
        public string ProjectID { get; set; }
        public string ProjectDescription { get; set; }
        public string PCBU { get; set; }
        public string AssignmentStartDt { get; set; }
        public string HoursPerDay { get; set; }
        public string ProjectRole { get; set; }
        public string employee_status { get; set; }
        public string ReleaseMonth { get; set; }
        public string ReportingManager { get; set; }
        public string PMName { get; set; }
        public string SPMName { get; set; }
        public string EDName { get; set; }
        public string GHName { get; set; }
        public string GLName { get; set; }
        public string SGLName { get; set; }
        public string PyramidAccount { get; set; }
        public string RMBU { get; set; }
        public string HR_BU { get; set; }
        public string DeptID { get; set; }
    }
}
