//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.DataAccessLayer.DataEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationDetail
    {
        public int VacationDetailId { get; set; }
        public Nullable<int> ResourceDetailId { get; set; }
        public Nullable<System.DateTime> VacationDate { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<bool> IsPlanned { get; set; }
        public Nullable<bool> IsBillable { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> Approvedby { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string Reason { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual ResourceDetail ResourceDetail { get; set; }
    }
}
